### ISSUE TITLE
crashing when deleting a group of saved

### ISSUE THREAD

**Issue by galenthurber** [teccheck/FastLyrics#48] opened 2024-10-06 18:23 UTC
Crash
Select a few saved entries then 
Tap on delete icon which is missing
Pie 9 
Not rooted
[2024-09-25_13.17.zip](https://github.com/user-attachments/files/17270532/2024-09-25_13.17.zip)

**Comment by TecCheck** [comment] 2024-11-19 07:56
Unfortunately I cannot reproduce this crash. Maybe it's already fixed in the current code.
Thanks for providing a log file, but it doesn't actually contain any log output from FastLyrics

**Closed** 2024-11-20 20:00 UTC
